apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  lables:
    app: nginx
spec:
  replicas: 3    #run 3 instances
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports: 
        - containerPort: 80
        
