apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: nginx:stable-alpine3.20