apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp
  labels:
    name: goapp
spec:
  replicas: 3
  selector:
    name: goapp
  template:
    metadata:
      labels:
        name: goapp
    spec:
      containers:
      - name: goapp
        image: nginx:stable-alpine3.20
        ports:
        - containerPort: 80